### ISSUE TITLE
DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by corruptmemry** [oceanroleplay/discord.ts-example#10]
Hello! 

I'm trying to run this example but i'm getting this error:
```
      throw new DiscordAPIError(data, res.status, request);
            ^
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/corruptmemory/dists2/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/corruptmemory/dists2/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async GuildApplicationCommandManager.fetch (/home/corruptmemory/dists2/node_modules/discord.js/src/managers/ApplicationCommandManager.js:97:18)
    at async Client.initGuildApplicationCommands (file:///home/corruptmemory/dists2/node_modules/discordx/src/Client.ts:379:33)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Client.initApplicationCommands (file:///home/corruptmemory/dists2/node_modules/discordx/src/Client.ts:351:5)
    at async Client.<anonymous> (file:///home/corruptmemory/dists2/src/client.ts:22:3) {
  method: 'get',
  path: '/applications/887921585812537364/guilds/894231038228856922/commands',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}
```
On pure NodeJS (without TS) everything is works.

**Comment by oceanroleplay** [comment]
Please follow steps described at https://discord-ts.js.org/docs/decorators/commands/slash#authorize-your-bot-to-use-slash-commands

**Comment by oceanroleplay** [comment]
If you are not planning to use guild command, comment [this line](https://github.com/oceanroleplay/discord.ts-example/blob/main/src/client.ts#L16), And it will use global commands instead.
